# Generated by Django 4.1.1 on 2022-09-30 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Поставщик')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('contact_person', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Контактное лицо')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Адрес')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Поставщика',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('availability', models.BooleanField(default=True, verbose_name='Наличие')),
                ('remainder', models.FloatField(blank=True, default=0, verbose_name='Остаток кг/шт')),
                ('purchase_price', models.FloatField(verbose_name='Закупка грн')),
                ('sale_price', models.FloatField(verbose_name='Продажа грн')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение')),
                ('notes', models.TextField(blank=True, max_length=1000, verbose_name='Заметка')),
                ('barcode', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Штрихкод')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.category', verbose_name='Категория')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-added_at'],
            },
        ),
    ]
